### PR TITLE
Feature : Added events search (#14)

### LINKED ISSUE #14: Add search feature
Add a search bar on the top to search based on the text content of the entries, and hide items based on that.

### PR DESCRIPTION
**Pull request by gautamjuyal**
## Fixes #14 

This PR adds events search feature to the calendar

## Changes/Updates

1. Added SearchHeader component to the project.
2. Removed directly passing `events.json` to `FullCalendar` component. `events.json` is now manually imported to `App.jsx`.
3. Due to manual import, devs are now required to move events.json from `root` directory to `src` directory in development. Same has been updated in the `Readme.md` file.

## Features

1. The search works once the user clicks the search button after passing a search string in the input.
2. Search feature checks for availability of search string in all the event's title and description.
3. When search is in use, only the events matching the search string are displayed throughout the calendar.
4. If the search string doesn't match any any string, no events are displayed in the calendar.
5. Once the search box is cleared, the calendar resets and loads all available events.

## Screenshots

1. Calendar
Screenshot (374)

2. Calendar (when searched for an event)
Screenshot (377)

3. Dark Mode
Screenshot (375)

4. Mobile view
Screenshot (378)

## Suggestions and improvements

Since this is the first iteration of search in the project it might not be perfect, thus any improvements and suggestions are very much appreciated

### CODE REVIEW

**Comment by TheJuanAndOnly99** [comment]
Hi @gautamjuyal looks and works great for a 1st iteration! I think we can start with this. Would like an additional review from @maoo and/or @mimiflynn if possible. But I would be happy to roll this out and then we can work on improvements.

**Comment by gautamjuyal** [comment]
Sounds good. Thanks for the review!

**Review by maoo — APPROVED** [review]
LGTM

**Comment by TheJuanAndOnly99** [comment]
Hey @gautamjuyal I had to revert this as it broke the build. It cannot resolve ./events.json probably because the file is added to the dist folder and not the root. See https://github.com/finos/calendar/actions/runs/7462231946/job/20304079088#step:4:20.

**Comment by gautamjuyal** [comment]
@TheJuanAndOnly99 I had my doubts around this. Do you think changing the import to this should work?
```bash
import events.json from './dist/events.json
```

**Comment by TheJuanAndOnly99** [comment]
We can try but in the action we would have to do [`npm run getEvents` ](https://github.com/finos/calendar/actions/runs/7462860949/workflow#L38) before doing [`npm run build`](https://github.com/finos/calendar/actions/runs/7462860949/workflow#L30)

**Pull request merged**
