### PR TITLE
Feature : Added events search (+Added Fix) (#14)

### LINKED ISSUE #14: Add search feature
Add a search bar on the top to search based on the text content of the entries, and hide items based on that.

### PR DESCRIPTION
**Pull request by gautamjuyal**
## Fixes #14 

This PR adds events search feature to the calendar

## Changes/Updates

1. Added SearchHeader component to the project.
2. Removed directly passing `events.json` to `FullCalendar` component. `events.json` is now manually imported to `App.jsx`.
3. Due to manual import, devs are now required to move events.json from `root` directory to `src` directory in development. Same has been updated in the `Readme.md` file.

## Features

1. The search works once the user clicks the search button after passing a search string in the input.
2. Search feature checks for availability of search string in all the event's title and description.
3. When search is in use, only the events matching the search string are displayed throughout the calendar.
4. If the search string doesn't match any any string, no events are displayed in the calendar.
5. Once the search box is cleared, the calendar resets and loads all available events.

## Screenshots

1. Calendar
Screenshot (374)

2. Calendar (when searched for an event)
Screenshot (377)

3. Dark Mode
Screenshot (375)

4. Mobile view
Screenshot (378)

## Suggestions and improvements

Since this is the first iteration of search in the project it might not be perfect, thus any improvements and suggestions are very much appreciated 

## Caveats

Even though import statement is changed (which was causing error), it is still unsure whether the change fixes the issue. Will need to be tested on deployment.

### CODE REVIEW

**Comment by TheJuanAndOnly99** [comment]
Hi @gautamjuyal sorry for the delay. Could you resolve the conflicts? I'll review after and hopefully we can merge this time!

**Comment by gautamjuyal** [comment]
Sure. I'll start resolving the conflicts. There's one thing I wanted to ask, do we have any way to deploy a branch, so that we test the changes in the branch first?

**Comment by TheJuanAndOnly99** [comment]
> Sure. I'll start resolving the conflicts. There's one thing I wanted to ask, do we have any way to deploy a branch, so that we test the changes in the branch first?

We need to look into this but I think it's related to this issue https://github.com/finos/calendar/issues/95. I'll discuss this with @maoo.

**Comment by TheJuanAndOnly99** [comment]
@gautamjuyal I cannot send a PR to your branch. Can you either grant me permission or change the action to be like this:

```
name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.10.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install
        run:  npm ci

      - name: Setup environment
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output calendar-service-account.json calendar-service-account.json.gpg
        env:
          PASSPHRASE: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PASSPHRASE }}

      - name: Get events from Google API
        run: npm run getEvents

      - name: Build
        run: npm run build

      - name: Add CNAME in dist folder
        run: cp CNAME dist
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist
        if: github.event_name != 'pull_request'

```

Thanks!

**Comment by gautamjuyal** [comment]
There is an error with GPG this time
`gpg: gcry_kdf_derive failed: Invalid data
gpg: decryption failed: No secret key
Error: Process completed with exit code 2.`

**Comment by gautamjuyal** [comment]
I think this issue persists because of PASSPHRASE secret getting restricted to selected branches. I tried using my local passphrase but it doesn't work, since the PR has the original `calendar-service-account.json.gpg` file.

**Comment by TheJuanAndOnly99** [comment]
Thanks again @gautamjuyal! Sorry for the delay.

**Pull request merged**
